### PR TITLE
feat: Add inclusion directive when extracting documentation

### PR DESCRIPTION
**Pull request by gwhitney**
When `simple` is processing a match to a "semiliterate" pattern,
  and encounters `{! FILENAME YAML !}`, it will interpolate the
  contents of FILENAME as extracted according to the parameters in
  YAML (with the same semantics as the extraction parameters of
  a "semiliterate" pattern).

### CODE REVIEW

**Comment by gwhitney** [comment]
Second chunk, as discussed. Once this (quite possibly with revisions at your request ;-) is merged, I will submit the final step of folding the docs of `simple` into its source.

**Comment by athackst** [comment]
This seems super complicated for a plugin called "simple"

The addition of semiliterate actually plays really nicely with mkdocstrings (see #89 for example).  In general, this seems like a preferable approach to documenting APIs, as opposed to making inclusion markers.

This PR also highlights an issue, which is that it can only search through things that it's pattern matching for snippet inclusion, with the workaround of streaming all the files.  To me, this indicates it might be better off as a separate plugin that can process the extracted markdown files in a similar way that mkdocstrings is working.

**Comment by gwhitney** [comment]
mkdocstrings is great for pulling individual api documentation into Markdown files, but although it's officially language-agnostic, it needs a separate handler for each language and right now there's only a python handler. It's also not a generic, flexible inclusion directive, which is what you really need for "user manual" or other narrative-type documentation, as opposed to a more formal, structured "api-reference style" documentation.

The primary point for me of the original semiliterate effort was to have automatic extraction _and_ manual inclusion with **exactly** the same parameters and controls. It's precisely that uniformity that is deserving of the name "simple," and is what makes the tool so powerful for combined documentation and code in a style that provides a fair amount of the advantage of Knuth's literate style, with much less of the cumbersomeness. As one example, if a PR along the lines of this one could be agreed on, then the next PR that combines documentation and code was going to use the docstring of the SimplePlugin for three purposes: as a very reasonable docstring for the class; to generate the sample usage in the generated docsite; and to extract the config_scheme for the plugin directly in the actual running code, so that in the future updating options and/or defaults in just this one place would update all three aspects in sync. To me that sort of DRYness is a big win of (semi)literate programming.

If this perspective moves you at all, feel free to re-open this PR and let me know and I will be happy to continue the integration. In the meantime, with the reorganization from #85, I can simply pursue the option I suggested earlier: produce a plugin which will inherit from simple, rather than be a branch of it, which will provide clean code separation and which, I feel, will be fully respectful and supportive of your project. Thanks so much for working with me on this!

**Comment by athackst** [comment]
It sounds like what you want is templating.  I agree templating can be super useful for documentation.

I've added another example in #89 using [mkdocs-macros-plugin](https://mkdocs-macros-plugin.readthedocs.io/en/latest/) which uses [jinja2](https://jinja.palletsprojects.com/en/2.11.x/).  I did have to update the plugin a bit to well support this, but those changes should be non-breaking.  I've used Jinja in the past to create a matrix of [dockerfiles](https://github.com/athackst/dockerfiles/blob/main/template/ros.dockerfile.jinja) and their supporting [readme](https://github.com/athackst/dockerfiles/blob/main/template/readme.md.jinja) files.

You're of course free to do whatever works best for you, but you may benefit from using a well-developed template language.  I'm personally really excited about this combination, and I thank you for your contribution!

**Comment by gwhitney** [comment]
Yes, I thought about the macros plugin, but jinja2 seemed very heavyweight for simply extracting snippets from other files. The
`{% include FILE %}` directive doesn't (seem to) have any straightforward options for trimming what gets included. I worked a bit on the "markdown-include" extension, but got such a long stream of (IMO) random and unclear-as-to-purpose feedback from the maintainer (unlike your own cogent and useful feedback) that I despaired of any hope of getting that to where it would be useful for me.

Then I saw your 'simple' plugin and thought how nice it would be to have unified markdown extraction and inclusion -- that would be everything I would need to generate the documentation sites I want to, and there would be only one syntax to remember. So that's the genesis of semiliterate -- from my perspective it was always about the fact that extraction and inclusion are really the same operation.

(For example, I see that in your latest plugin.py with incorporated markdown, you needed to add different-format markdown start/stop triggers for the configuration-scheme documentation anyway, plus you need a whole extra plugin for processing them. With the `{! ... !}` inclusion syntax, which comes close to free now that you have extraction, I think your source file would be more uniform in structure, and simple would do everything you want by itself. Sorry, couldn't resist one more attempt at persuasion... ;-)

In any case, the semiliterate extension is "done" at http://code.studioinfinity.org/glen/mkdocs-semiliterate (doc site at http://studioinfinity.org/semiliterate). I won't put it on PyPI or the MkDocs plugin list until there's a release of mkdocs-simple-plugin that supports the inheritance. (And in fact I included in my latest bugfix PR a slight refactoring that will prevent the inheriting class from having to completely reiterate the `extract_from` method just to change the class that's doing the extraction from StreamExtract to a class that inherits from StreamExtract, if that's OK.)

Anyhow, I'd be gratified if you want to give mkdocs-semiliterate a quick look-over. If there's anything you'd like changed before I release it, I'd be happy to, and if you happen to want any of the bits of it to be in mkdocs-simple-plugin (there are two or three small tweaks that are independent of inclusion) I'd be happy to make a PR. Just let me know. Pleasure working with you.

**Comment by athackst** [comment]
My hesitation is that this syntax

```
{! plugin.py ---
--
  | start: '[*]SimplePlugin.config_scheme'
  | terminate: '^\s*\)'
  | replace:
  | - ["\\('(.*)',\\s*$", '\1\n']
  | - ['config_options.Type.*?default=([^\)]*)', ':  (\1)']
  | - '^\s*#(.*\s*)$'
  | !}
```

Is what I would call "very heavy".  I would not expect a casual user to be able to come up with the appropriate configuration to include a subsection of code, and it seems pretty hard to pre-include an appropriate default.

I could, however, get behind a syntax that specifies a temp file to extract to (or hold in memory) like 

``` 
# md plugin.snippet
# comments to include
# /md
```

Where `plugin_config` is a filename specified in the markdown comment marker (which the user specifies)

Which then gets included using

```
{! plugin.snippet !}
```

Conceivably, if you wanted a more advanced configuration here, you would then add that to the mkdocs.config file using the unique identifier `# md plugin.snippet` for the start.

**Comment by gwhitney** [comment]
No need for us to hash this over further. I think our conceptualizations of this are different enough that my mkdocs-semiliterate deriving from your now-enhanced mkdocs-simple-plugin is a solid way to go, and once we get PR #93 ironed out (I will update tomorrow) there is very little code in mkdocs-semiliterate, so it's a very clean separation.

I only want to add that I agree that the inclusion instance you quote **is** very heavy. But that's because I am transforming an mkdocs config_scheme value, in its particular syntax, into a markdown definition list, in its completely different idiosyncratic syntax. Since they basically have just the same pieces of information, it can be done, but because the syntaxes bear little resemblance to each other, it's intricate. I would not expect to do something like that routinely, but I was glad I had the power to do it so that I would not be reiterating the same information in two places.

**Pull request closed without merging**
