### PR TITLE
Support dirtyreload so that only updated files get rebuilt

### LINKED ISSUE #441: Incremental file building when --dirtyreload is set
Hey there,

I've been playing around with this plugin recently and have noticed some significant performance issues related to live reloading. The performance of the plugin is perfectly acceptable for a single documentation build, but it appears that _any_ file change while this plugin is active leads the plugin to rebuild _all_ files that it's watching.

I've played around with the code a bit, and I think it's relatively easy to:

* Know when the user has --dirtyreload set (from the MkDocsConfiguration)
* Track the most recent build that mkdocs-simple performed (e.g., using a global within plugin.py, although there may be a better way to do this)
* Filter the list of files that will be operated on by the plugin in both merge_docs and build_docs in simple.py

The one thing I haven't been able to figure out is something that's going on under the hood leading to this error (during the build step):

```
[Errno 2] No such file or directory: <file that was not changed>
```

So it seems like something is expecting this file to be output, but I haven't been able to tell what.

Given this, two questions for you:

1. If we can figure out how to make this work, would you be willing to merge a change like this assuming I can make it reasonable
2. If so, could you please point me in the right direction to complete this?

Thanks!

### PR DESCRIPTION
**Pull request by athackst**
Co-authored-by: @jkaye2012

Closes #441

### CODE REVIEW

**Comment by jkaye2012** [comment]
Hey there - just had a chance to give this a try this morning. Unfortunately from what I'm seeing, I think all files may still be getting rebuilt (or perhaps I'm misunderstanding how this is meant to work).

Running the first time, I see this as expected:

```
WARNING  -  A 'dirty' build is being performed, this will likely lead to inaccurate navigation and other links within your site. This option is designed for site
            development purposes only.
INFO     -  Documentation built in 121.27 seconds
INFO     -  [15:28:56] Watching paths for changes: '/tmp/mkdocs_simple_repoo60u600b', 'mkdocs.yml', '_doc', 'README.md',
            'bt/analytics/flink/examples/how_to_run_beginner_flink_jobs.md', 'bt/analytics/flink/examples/how_to_run_custom_metrics_job.md',
... many more paths
```

I can then browse docs as usual.

Upon changing a file, I see this:

```INFO     -  [15:29:51] Detected file changes
INFO     -  Building documentation...
WARNING  -  Config value 'dev_addr': The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server.
            However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead.
INFO     -  mkdocs-simple-plugin: build_docs_dir: /tmp/mkdocs_simple_repob26prgbu
root dir: /repo/, src dir: /repo/.
```

But the build doesn't appear to proceed and the site ends up hung (seemingly permanently).

**Comment by jkaye2012** [comment]
It did eventually rebuild, but took a very long time. Much longer than I remember from last week!

**Comment by athackst** [comment]
hmm.. I think I didn't keep the venv ignore setting you had which is probably resulting in your setup not working correctly.  I added common folders to .mkdocsignore so that they wouldn't be included in a rebuild.

Try again?

**Comment by jkaye2012** [comment]
Gave that a try with the same result. The test I'm running for this is on our production repository using a system-level installation of the plugin, so I don't think any of the in-repo files here would have an effect. The list of files that the plugin says it's watching seems to be correct so far as I can tell (our repo is quite large, so it's hard to be sure, but I haven't noticed anything that seems off).

I'm going to give this another try a bit later after tossing a few prints in so that we can see what's going on. The fact that it takes longer to re-generate than it does to generate from scratch makes me think that there is something "recursive" going on, so it's also very possible that this is an issue with the way that I have things set up. Will report back!

**Comment by jkaye2012** [comment]
Facepalm. I cloned the repo and installed it locally, but didn't check out the feature branch before doing so :facepalm:

Everything seems to be working perfectly, sorry about that!

**Comment by jkaye2012** [comment]
I'm going to close #442 in lieu of this

**Comment by athackst** [comment]
Cool!  Good to here. I'll merge in then :smile:

**Comment by jkaye2012** [comment]
Awesome! Is there anywhere I can follow to see when this makes it into a release?

**Comment by athackst** [comment]
You can go to watch -> custom -> releases on the repo and you should get an alert when the next release is made :rocket:

**Pull request merged**
